name: CI/CD Pipeline

# Trigger the workflow on push or pull request events
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Define the jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Install dependencies
    - name: Install dependencies
      run: echo "manoj Kumar Unnam"

    # Run tests
    - name: Run tests
      run: sh 'echo test'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Run tests
      run: echo "Deploying application..."
        # Add your deployment script here
